name: Test CosmosDb pipeline on Linux

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: Run .NET unit tests (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Run All tests
        run: dotnet test